# Generated by Django 3.2 on 2022-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_dimensions_and_composition',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='composition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
