# Generated by Django 3.2 on 2022-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220505_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
